const cv='https://ikekonglp.github.io/lingpenk_cv.pdf';
const lab='https://hkunlp.github.io/people/';
// These notes distinguish dated CV history from current, sometimes undated, homepages.
export const profiles = {
  'Lin Zheng':{home:'https://lzhengisme.github.io/',current:'香港大学',role:'博士生',history:'2021起；博士生（CV）',relation:'导师—学生',quote:'supervised by Prof. Lingpeng Kong',research:'高效序列模型、线性注意力、字节表示与非自回归生成',issue:'主页为第五年博士生；毕业时间未公开。'},
  'Jiacheng Ye':{home:'https://jiacheng-ye.github.io/',current:'待核验（主页仍为香港大学博士生；实验室列为2026校友）',role:'博士生/毕业状态待核验',history:'2022起；博士生；与Tao Yu共同指导（CV）',relation:'导师—学生；共同指导',quote:'co-supervised by Prof. Lingpeng Kong and Prof. Tao Yu',research:'扩散语言模型、规划与数据合成',issue:'离组日期及当前单位待核验；主页与校友页存在更新时差。'},
  'Shansan Gong':{home:'https://summmeer.github.io/',current:'香港大学',role:'博士生',history:'2023起；博士生（CV）',relation:'导师—学生',quote:'I am a PhD candidate at HKU, supervised by Lingpeng Kong.',research:'扩散语言模型、长上下文、可控生成与推理',issue:'主页明确为精选论文；CV以外成果可能漏项。'},
  'Qintong Li':{home:'https://qtli.github.io/',current:'Qwen（依据导师2026-01-27 CV；当前任职仍待新公告复核）',role:'研究科学家（CV）',history:'2021-2025；香港大学博士生；毕业后Qwen研究科学家（CV）',relation:'导师—学生',quote:'Qintong Li (2021-2025), now a research scientist at Qwen',research:'模型对齐、数学推理与评价',issue:'个人主页残留final-year表述，与CV毕业/去向记录并列；入职月份未公开。'},
  'Jiahui Gao':{home:'https://sumilergao.github.io/jiahuig.hku/',current:'华为诺亚方舟实验室（2025论文署名；当前官方任职待核验）',role:'当前职位未公开',history:'2019-2023；香港大学博士生；2025论文署名华为',relation:'导师—学生；共同指导',quote:'supervised by Stephen M.S. LEE and Lingpeng Kong',research:'预训练、数据合成、多模态与扩散模型',issue:'主页停留于博士期间；不能用2025论文单位确定2026当前任职。'},
  'Sheng Wang':{home:'https://forence1999.github.io/',current:'未公开',role:'未公开',history:'2024-2025；博士生；与Chuan Wu共同指导（CV）',relation:'导师—学生；共同指导',quote:'Sheng Wang (2024-2025)',research:'对话系统、低秩适配与智能体',issue:'成员链接/about返回404；CV与校友页支持历史指导，当前职位未核实。'},
  'Chang Ma':{home:'https://chang-github-00.github.io/-changma/',current:'华盛顿大学',role:'博士后',history:'2022起；香港大学博士生；现为华盛顿大学博士后，准确分界待核验',relation:'导师—学生；共同指导',quote:'postdoctoral researcher at the University of Washington',research:'自主、高效、可信的科学智能体',issue:'个人主页博士时间至2026-04，实验室校友页为2025；毕业及离组年份冲突待核验。'},
  'Xueliang Zhao':{home:'',current:'香港大学（CV；现况待核验）',role:'博士生（CV）',history:'2022起；博士生（CV）',relation:'导师—学生',quote:'Xueliang Zhao (2022-)',research:'数学推理、题目合成与形式证明',issue:'仅CV与论文历史信息；独立主页和当前学生状态未核验。'},
  'Yiheng Xu':{home:'https://yihengxu.github.io/',current:'OpenAI',role:'研究员',history:'2022起；香港大学博士生；主页现为OpenAI研究员，入职时间未公开',relation:'导师—学生；共同指导',quote:'Researcher OpenAI',research:'文档理解、编码智能体与GUI智能体',issue:'CV仍列2022起在读，实验室列2025校友；毕业日期和OpenAI入职日期待核验。'},
  'Jingwei Dong':{home:'',current:'香港大学（CV；现况待核验）',role:'博士生（CV）',history:'2025起；博士生；与Chuan Wu共同指导（CV）',relation:'导师—学生；共同指导',quote:'Jingwei Dong (2025-)',research:'依据共同论文：参数效率与扩散代码模型',issue:'独立主页、完整论文列表及当前状态未核验。'},
  'Zhihui Xie':{home:'https://zhxie.site/',current:'香港大学',role:'博士生',history:'2024起；博士生；2025暑期Meta实习（主页）',relation:'导师—学生；共同指导',quote:'Lingpeng Kong and Qi Liu',research:'批评模型、强化学习、对齐与扩散生成',issue:'博士结束日期未公开；时间按CV而非主页年级倒推。'},
  'Xijia Tao':{home:'https://xijia-tao.github.io/',current:'香港大学',role:'博士生',history:'2024起；博士生（CV）',relation:'导师—学生',quote:'PhD',research:'多模态深度研究与扩散模型',issue:'主页论文选择范围与完整性未声明；毕业日期未公开。'},
  'Jing Xiong':{home:'https://menik1126.github.io/',current:'香港大学',role:'博士生',history:'2024起；博士生（CV）',relation:'导师—学生；共同指导',quote:'supervised by Prof. Yi Huang and Prof. Lingpeng Kong',research:'高效语言模型推理、形式证明与数学推理',issue:'CV共同指导者Ngai Wong，个人主页为Yi Huang；不将两人视为同一人，共同指导者待核验。'},
  'Chenxin An':{home:'',current:'香港大学（CV；现况待核验）',role:'博士生（CV）',history:'2023起；博士生（CV）',relation:'导师—学生',quote:'Chenxin An (2023-)',research:'对比生成、长上下文和扩散模型',issue:'个人主页及完整论文列表未核验。'},
  'Zhenyu Wu':{home:'',current:'上海交通大学（CV；现况待核验）',role:'博士生（CV）',history:'2023起；上海交通大学博士生（CV）',relation:'导师—学生',quote:'Zhenyu Wu (2023-, SJTU)',research:'依据共同论文：扩散搜索与规划',issue:'联合培养安排、具体起止日期及独立主页未核验。'},
  'Xiachong Feng':{home:'https://xcfeng.net/',current:'香港大学',role:'博士后',history:'2024起；博士后；与Chuan Wu共同主持（CV）',relation:'博士后；共同指导',quote:'postdoctoral',research:'递归自我改进、智能体系统与社会推理',issue:'博士后结束日期未公开；博士导师Bing Qin与Xiaocheng Feng来自个人主页。'},
  'Tao Yu':{home:'https://taoyds.github.io/',current:'香港大学',role:'助理教授',history:'合作期间教师身份已确认；准确任职起止待核验',relation:'共同指导',quote:'Assistant Professor of Computer Science at The University of Hong Kong',research:'自然语言处理、代码和数据科学智能体、数字与物理环境交互',issue:'共同指导由孔令鹏CV支持；不据同校推断同系任职时间重叠。'},
  'Qi Liu':{home:'https://leuchine.github.io/',current:'香港大学；Reka AI（共同创办人）',role:'助理教授',history:'合作期间教师身份已确认；准确任职起止待核验',relation:'共同指导',quote:'Assistant Professor',research:'自然语言处理、机器学习、多模态模型',issue:'Qi Liu存在同名风险；仅按本人主页、CV共同指导和对应论文链确认。'},
  'Chuan Wu':{home:'https://i.cs.hku.hk/~cwu/',current:'香港大学',role:'教授',history:'合作期间教师身份已确认；准确任职起止待核验',relation:'共同指导',quote:'Professor',research:'分布式机器学习、云计算与老年照护',issue:'CV确认共同指导Sheng Wang/Jingwei Dong及共同主持Xiachong Feng；公开项目职责未核验。'},
  'Noah A. Smith':{home:'https://homes.cs.washington.edu/~nasmith/',current:'未公开（当前页面正文未成功提取）',role:'当前职称待核验',history:'2017博士论文委员会共同主席；2015-2022共同论文署名华盛顿大学',relation:'导师—学生（孔令鹏为学生）',quote:'Noah A. Smith (co-chair)',research:'以已确认一作论文和共同论文为限',issue:'当前学校职称及任职时间待核验；导师关系依据孔令鹏CV第1页。'},
  'Chris Dyer':{home:'',current:'未公开',role:'当前职称待核验',history:'2017博士论文委员会共同主席；共同论文署名CMU与DeepMind',relation:'导师—学生（孔令鹏为学生）',quote:'Chris Dyer (co-chair)',research:'结构化语言模型、句法和表示学习',issue:'导师关系依据CV；当前职称、部门与任职时间未核验。'},
  'Dani Yogatama':{home:'https://dyogatama.github.io/',current:'南加州大学；Reka AI',role:'副教授；首席执行官',history:'2016-2022；DeepMind；CMU博士2010-2015；当前USC任职起始待核验',relation:'同门；论文合作者',quote:'Noah A. Smith',research:'机器学习、语言理解与通用智能',issue:'与孔令鹏同一博士导师有CV/主页支持；不能只凭DeepMind重叠经历认定同部门同事。'},
  'Zhiyong Wu':{home:'https://lividwo.github.io/zywu.github.io/',current:'字节跳动Seed',role:'研究科学家',history:'2020孔令鹏组访问学生（CV）；后在上海人工智能实验室；当前ByteDance Seed',relation:'论文合作者；曾任访问学生',quote:'ByteDance Seed',research:'操作系统智能体、语言模型与数据合成',issue:'校友页仍列上海人工智能实验室；现职采用本人主页，入职日期未公开；不推定孔令鹏为其博士导师。'},
  'Jiangtao Feng':{home:'https://jiangtaofeng.github.io/',current:'GenSI（清华AIR与上海人工智能实验室联合团队）',role:'具体职位未公开',history:'曾任上海人工智能实验室研究负责人、字节跳动高级研究员；具体起止未公开',relation:'论文合作者',quote:'a joint team from Tsinghua AIR and Shanghai AI Lab',research:'人工智能可扩展性、通用性与科学应用',issue:'历史岗位时间与共同项目职责未公开。'},
  'Zhenguo Li':{home:'https://zhenguol.github.io/',current:'华为诺亚方舟实验室',role:'AI Theory方向负责人；香港科技大学兼职教授',history:'合作期间华为科研人员；准确任职起止待核验',relation:'论文合作者',quote:'Noah',research:'生成式人工智能、数学与科学',issue:'共同项目职责、任职起止未公开；兼职教师任期未核验。'},
  'Renjie Pi':{home:'https://pi-renjie.github.io/',current:'香港科技大学（主页）',role:'博士生',history:'2021起；香港科技大学博士生；本科香港大学2016-2021',relation:'论文合作者',quote:'Tong Zhang',research:'以数据为中心的多模态模型优化',issue:'本人导师为Tong Zhang/Xiaofang Zhou，未见孔令鹏指导证据；结束时间未公开。'},
  'Haiteng Zhao':{home:'https://zhao-ht.github.io/',current:'上海人工智能实验室',role:'研究员',history:'北京大学博士2025毕业；现上海人工智能实验室，入职月份未公开',relation:'论文合作者',quote:'Shanghai AI',research:'推理、智能体和科学应用',issue:'历史身份具体起始与共同项目未核验。'},
  'Lei Li（香港大学）':{home:'https://lilei-nlp.github.io/',current:'香港大学；小米MiMo团队（主页列核心贡献者）',role:'博士生',history:'2023-09起；香港大学博士生；2020-2023北京大学硕士',relation:'导师—学生；共同指导',quote:'co-supervised by Prof. Lingpeng Kong and Prof. Qi Liu',research:'多模态模型、上下文学习与模型评价',issue:'只纳入可与本人论文列表或nlp.lilei邮箱/单位核对的记录；不合并CMU/UCSB同名教师。'},
};
export const profileEvidence=(name,p)=>`${p.home||cv}；访问2026-09-17；原文依据：“${p.quote}”。历史指导/时间另见${cv}第1-2页（版本2026-01-27）；校友更新见${lab}。核验状态：公开身份部分确认；局限见待核验问题。`;
export const hkuLeiIds=new Set([38,40,55,60,68,74,137,149,168]);
export const facultyNames=new Set(['Tao Yu','Qi Liu','Chuan Wu','Noah A. Smith','Chris Dyer','Dani Yogatama']);
