import {useEffect,useMemo,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import {ArrowDownToLine,ArrowLeft,ArrowUpRight,BookOpen,Check,ChevronDown,ChevronLeft,ChevronRight,ExternalLink,FileText,GraduationCap,Info,Library,Search,SlidersHorizontal,UserRound,Users,X} from 'lucide-react';
import * as echarts from 'echarts/core';
import {BarChart,GraphChart} from 'echarts/charts';
import type {BarSeriesOption,GraphSeriesOption} from 'echarts/charts';
import {GridComponent,TooltipComponent} from 'echarts/components';
import type {GridComponentOption,TooltipComponentOption} from 'echarts/components';
import {CanvasRenderer} from 'echarts/renderers';
import ReactMarkdown from 'react-markdown';

type Row=Record<string,string>;
type ChartOption=echarts.ComposeOption<BarSeriesOption|GraphSeriesOption|GridComponentOption|TooltipComponentOption>;
echarts.use([BarChart,GraphChart,GridComponent,TooltipComponent,CanvasRenderer]);
type Paper=Row&{eligible:boolean;pdf:string|null};
type Section={title:string;content:string};
type Advisor={id:string;info:Row;papers:Paper[];collaborators:Row[];signatures:Row[];collaboratorPapers:Row[];issues:Row[];reports:{research:Section[];collaboration:Section[]};missing:string[];files:{name:string;url:string}[];coverage:Record<string,string|number>;portrait:string};
type View='basic'|'research'|'collaborators';
const ids=(s:string)=>s?.split(';').map(s=>s.trim()).filter(Boolean)??[];
const unique=(s:string[])=>[...new Set(s)].sort((a,b)=>a.localeCompare(b,'zh-CN'));
const links=(s:string)=>s?.match(/https?:\/\/[^\s；，。<>]+/g)??[];
const asset=(path:string)=>`./${path}`;
const palette=['#167766','#447eae','#b7637d','#ba852d','#759460','#7a73a4','#5b9598','#8d8579'];
function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
function External({href,children}:{href:string;children:ReactNode}){return <a href={href} target="_blank" rel="noreferrer" className="external">{children}<ArrowUpRight size={14}/></a>;}
function Empty({text='尚未整理'}:{text?:string}){return <div className="empty"><Search size={23}/><p>{text}</p></div>;}
function Markdown({content,onPaper}:{content:string;onPaper:(id:string)=>void}){
  return <div className="markdown"><ReactMarkdown components={{a:({href,children})=>href?.startsWith('#paper-')?<button className="inline-link" onClick={()=>onPaper(href.slice(7))}>{children}</button>:<a href={href} target="_blank" rel="noreferrer">{children}</a>}}>{content}</ReactMarkdown></div>;
}
function Chart({option,label,height=255,onClick}:{option:ChartOption;label:string;height?:number;onClick?:(name:string)=>void}){
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);chart.setOption(option);if(onClick)chart.on('click',p=>onClick(p.name));const observer=new ResizeObserver(()=>chart.resize());observer.observe(ref.current);return()=>{observer.disconnect();chart.dispose();};},[option,onClick]);
  return <div ref={ref} style={{height}} className="chart" role="img" aria-label={label}/>;
}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:ReactNode;wide?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const el=ref.current;el?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;el?.close();};},[]);
  return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" title="关闭" aria-label="关闭" onClick={onClose}><X size={20}/></button></div><div className="modal-body">{children}</div></dialog>;
}
function Stat({value,label,caption}:{value:string|number;label:string;caption?:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong>{caption&&<small>{caption}</small>}</div>;}
function SignatureRatio({rows,field,label}:{rows:Row[];field:string;label:string}){const known=rows.filter(r=>['是','否'].includes(r[field]));const yes=known.filter(r=>r[field]==='是').length;return <div className="ratio"><span>{label}</span><strong>{known.length?`${Math.round(yes/known.length*100)}%`:'未核验'}</strong><div className="ratio-track"><span style={{width:known.length?`${yes/known.length*100}%`:'0%'}}/></div><small>{known.length?`${yes} / ${known.length} 篇已核验`:'暂无可计算分母'} · {rows.length-known.length} 篇待核验</small></div>;}

export default function App(){
  const [data,setData]=useState<Advisor[]>([]),[error,setError]=useState('');
  const [view,setView]=useState<View>('basic'),[advisorId,setAdvisorId]=useState('');
  const [query,setQuery]=useState(''),[department,setDepartment]=useState('全部院系'),[interest,setInterest]=useState('全部方向'),[admission,setAdmission]=useState('全部招生状态');
  const [showFilters,setShowFilters]=useState(false),[showSources,setShowSources]=useState(false),[showIssues,setShowIssues]=useState(false),[paperId,setPaperId]=useState<string|null>(null);
  const [selectedPerson,setSelectedPerson]=useState<string|null>(null);
  useEffect(()=>{fetch(asset('data/advisors.json')).then(r=>{if(!r.ok)throw new Error(`数据加载失败（${r.status}）`);return r.json();}).then(d=>{setData(d.advisors);setAdvisorId(d.advisors[0]?.id??'');}).catch(e=>setError(e.message));},[]);
  const advisor=data.find(a=>a.id===advisorId);
  const visible=data.filter(a=>(a.info['姓名']+a.info['中文名']).toLowerCase().includes(query.toLowerCase())&&(department==='全部院系'||a.info['院系']===department)&&(interest==='全部方向'||a.info['研究兴趣和方向'].split('；').includes(interest))&&(admission==='全部招生状态'||(admission==='有申请说明'?a.info['是否招收PhD'].startsWith('是'):!a.info['是否招收PhD'].startsWith('是'))));
  const matching=visible.some(a=>a.id===advisorId);
  const paper=advisor?.papers.find(p=>p['序']===paperId);
  const openPaper=(id:string)=>setPaperId(id);
  if(error)return <main className="loading"><Info/><h1>资料暂时无法加载</h1><p>{error}</p><button onClick={()=>location.reload()}>重新加载</button></main>;
  if(!advisor)return <main className="loading"><Library size={30}/><p>正在读取导师资料…</p></main>;
  const counted=advisor.papers.filter(p=>p.eligible);
  return <div className="app">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Library size={22}/></div><div><strong>港大 AI 导师研究</strong><span>香港大学 · 学术资料档案</span></div></div><div className="top-actions"><span className="local-dot">本地资料库</span><button className="text-button" onClick={()=>setShowSources(true)}><FileText size={16}/><span>来源与材料</span></button></div></header>
    <div className="filterbar"><div className="search-input"><Search size={17}/><input aria-label="搜索导师" placeholder="搜索导师，中英文姓名" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-btn small" title="清空搜索" onClick={()=>setQuery('')}><X size={14}/></button>}</div><select aria-label="选择导师" value={matching?advisorId:''} onChange={e=>{setAdvisorId(e.target.value);setSelectedPerson(null);setPaperId(null);}}>{!matching&&<option value="">没有匹配导师</option>}{visible.map(a=><option key={a.id} value={a.id}>{a.info['中文名']} / Lingpeng Kong</option>)}</select><button className={`filter-toggle ${showFilters?'selected':''}`} onClick={()=>setShowFilters(!showFilters)} aria-expanded={showFilters}><SlidersHorizontal size={16}/>筛选<ChevronDown size={14}/></button><span className="filter-count">{visible.length} 位导师</span><div className={`filter-options ${showFilters?'open':''}`}><select aria-label="院系筛选" value={department} onChange={e=>setDepartment(e.target.value)}><option>全部院系</option>{unique(data.map(a=>a.info['院系'])).map(v=><option key={v}>{v}</option>)}</select><select aria-label="研究兴趣筛选" value={interest} onChange={e=>setInterest(e.target.value)}><option>全部方向</option>{unique(data.flatMap(a=>a.info['研究兴趣和方向'].split('；'))).map(v=><option key={v}>{v}</option>)}</select><select aria-label="博士招生筛选" value={admission} onChange={e=>setAdmission(e.target.value)}><option>全部招生状态</option><option>有申请说明</option><option>未公开或不招生</option></select>{(interest!=='全部方向'||department!=='全部院系'||admission!=='全部招生状态')&&<button className="inline-link" onClick={()=>{setInterest('全部方向');setDepartment('全部院系');setAdmission('全部招生状态');}}>重置筛选</button>}</div></div>
    <div className="workspace"><aside className="sidebar"><div className="sidebar-label">导师档案</div><nav aria-label="主导航">{([{id:'basic',label:'基础信息',icon:UserRound},{id:'research',label:'研究方向',icon:BookOpen},{id:'collaborators',label:'合作者',icon:Users}] as const).map(item=><button key={item.id} onClick={()=>setView(item.id)} className={view===item.id?'active':''} aria-current={view===item.id?'page':undefined}><item.icon size={18}/>{item.label}{view===item.id&&<ChevronRight className="nav-arrow" size={15}/>}</button>)}</nav><div className="sidebar-note"><span className="sidebar-label">资料状态</span><span><i className="status-dot"/>部分核验完成</span><p>{advisor.info['抓取日期']}</p><button className="inline-link" onClick={()=>setShowIssues(true)}>未完成事项 <ArrowUpRight size={14}/></button></div><div className="sidebar-bottom"><span>HKU</span><small>School of Computing<br/>and Data Science</small></div></aside>
      <main className="main">{!matching?<Empty text="没有符合当前筛选条件的导师"/>:<>
        <div className="breadcrumb">导师档案 <ChevronRight size={13}/> 孔令鹏 <ChevronRight size={13}/> {view==='basic'?'基础信息':view==='research'?'研究方向':'合作者'}</div>
        <section className="profile-header"><div className="profile-identity"><img className="portrait" src={advisor.portrait} alt="孔令鹏，来源：HKU NLP Lab"/><div><div className="name-line"><h1>{advisor.info['中文名']}</h1><Badge tone="green">研究型教师</Badge></div><p className="english-name">Lingpeng Kong</p><p className="position">香港大学 · 助理教授 <span className="separator">/</span> HKU NLP Lab 共同负责人</p></div></div><div className="profile-links"><External href={advisor.info['个人主页']}>个人主页</External><External href={advisor.info['CV网址']}>学术 CV</External><span className="updated">资料采集于 {advisor.info['抓取日期']}</span></div></section>
        <div className="stats-row"><Stat label="已收录论文" value={counted.length} caption={counted.length?`${Math.min(...counted.map(p=>Number(p['年份'])))}–${Math.max(...counted.map(p=>Number(p['年份'])))} · 非完整成果统计`:'尚未整理'}/><Stat label="近三年论文" value={counted.filter(p=>Number(p['年份'])>=2024&&Number(p['年份'])<=2026).length} caption="2024–2026 · 含预印本"/><Stat label="开放全文" value={advisor.papers.filter(p=>p['下载状态']==='已下载').length} caption="已下载并核对可读性"/><Stat label="Google Scholar 总引用" value={advisor.info['Google Scholar总被引次数']} caption={`统计日期：${advisor.info['引用统计日期']}`}/></div>
        {view==='basic'&&<Basic advisor={advisor} onIssues={()=>setShowIssues(true)} onSources={()=>setShowSources(true)}/>}
        {view==='research'&&<Research advisor={advisor} onPaper={openPaper}/>}
        {view==='collaborators'&&<Collaborators advisor={advisor} onPaper={openPaper} selected={selectedPerson} onSelect={setSelectedPerson}/>}
        <footer className="page-footer"><span>公开资料研究 · 仅收录孔令鹏</span><button className="inline-link" onClick={()=>setShowSources(true)}>查看来源与统计范围 <ArrowUpRight size={13}/></button></footer>
      </>}</main>
    </div>
    {paper&&<PaperDetail paper={paper} advisor={advisor} onClose={()=>setPaperId(null)}/>}
    {showSources&&<Modal title="来源与材料" onClose={()=>setShowSources(false)} wide><div className="notice"><Info size={17}/><div><strong>统计范围</strong><p>{String(advisor.coverage.description??'当前已整理的公开记录；非完整成果统计。')}</p></div></div><h3>原始材料</h3><div className="download-list"><a href={asset('data/导师信息汇总.csv')} download><FileText size={17}/>导师信息汇总.csv<ArrowDownToLine size={16}/></a>{advisor.files.map(f=><a key={f.url} href={asset(f.url)} download><FileText size={17}/>{f.name}<ArrowDownToLine size={16}/></a>)}<a href={asset('data/cv.pdf')} target="_blank" rel="noreferrer"><FileText size={17}/>导师公开 CV<ExternalLink size={16}/></a></div><h3>公开来源</h3><div className="source-list">{links(advisor.info['资料来源网址']).map(url=><External key={url} href={url}>{url}</External>)}</div><h3>核验状态</h3><p className="long-copy">{advisor.info['核验状态']}</p><h3>最近采集</h3><p>{advisor.info['抓取日期']} · CV 版本：2026-01-27</p></Modal>}
    {showIssues&&<Issues advisor={advisor} onClose={()=>setShowIssues(false)} onPaper={openPaper}/>}
  </div>;
}

function Basic({advisor,onIssues,onSources}:{advisor:Advisor;onIssues:()=>void;onSources:()=>void}){
  const i=advisor.info;
  const education=i['教育经历（本硕博院校信息及获取学位时间）'].split('\n');
  const jobs=i['任职'].split('\n');
  return <div className="basic-content"><div className="section-heading"><h2>基础信息</h2><button className="inline-link" onClick={onSources}>核验依据<ArrowUpRight size={14}/></button></div><div className="notice amber"><Info size={17}/><p>院系归属待核验：现有名单记为人工智能与数据科学系，个人主页与 CV 仍为计算机科学系。</p></div><div className="basic-columns"><section className="section"><h3>研究与任职</h3><dl className="info-grid"><dt>职称</dt><dd>{i['职称']}</dd><dt>岗位类型</dt><dd>{i['岗位类型（研究型/教学型/礼聘等）']}</dd><dt>实验室</dt><dd><External href="https://hkunlp.github.io/">HKU NLP Lab</External></dd><dt>院内职务</dt><dd>{i['院内及联聘职务']}</dd><dt>研究兴趣</dt><dd><div className="tags">{i['研究兴趣和方向'].split('；').map(t=><Badge key={t}>{t}</Badge>)}</div></dd></dl><div className="home-links"><External href={i['学校主页']}>学校目录</External><External href={i['ORCID网址']}>ORCID</External>{links(i['Google Scholar网址']).length?<External href={i['Google Scholar网址']}>Google Scholar</External>:<span>Scholar 主页待核验</span>}{links(i['DBLP网址']).length?<External href={i['DBLP网址']}>DBLP</External>:<span>DBLP 待核验</span>}</div></section><section className="section admissions"><div className="section-heading"><h3>博士招生</h3><Badge tone="green">有常设申请说明</Badge></div><div className="admission-number"><strong>1 ± 1</strong><span>人 / 年，主页所述通常规模</span></div><p>欢迎联系申请博士。具体年度名额和招生方向未公开，公告日期未标注。</p><dl className="info-grid compact"><dt>申请关注点</dt><dd>研究兴趣、对近期论文及工作稿的思考</dd><dt>年度有效性</dt><dd><Badge tone="amber">待核验</Badge></dd></dl><External href="https://ikekonglp.github.io/contact.html">查看导师申请说明</External></section></div><section className="section timeline-section"><div className="section-heading"><h3>教育经历</h3><span className="muted">来源：CV 第 1 页</span></div><div className="education-grid">{education.map((line,index)=>{const parts=line.split('；');return <div className="education-item" key={line}><div className="education-year"><GraduationCap size={18}/>{['2011','2015','2017'][index]}</div><h4>{parts[0]}</h4><p>{parts[1]}</p><small>入学时间未公开</small></div>;})}</div></section><section className="section"><div className="section-heading"><h3>工作与研究经历</h3><span className="muted">按公开年份排序 · 包含并行经历</span></div><div className="career-list">{[...jobs].reverse().map((line,index)=>{const p=line.split('；');return <div className="career" key={line}><div className="career-date">{p[2]}<span className={index===0?'current':''}/></div><div className="career-body"><h4>{p[0]}<span>{p[1]}</span></h4><p>{p[3]}</p></div></div>;})}</div></section><div className="verification-foot"><Check size={16}/><p>教育与任职按 CV 原文整理；未公开的月份、入学时间和工作职责不作推算。</p><button className="inline-link" onClick={onIssues}>查看未完成事项</button></div></div>;
}

function Research({advisor,onPaper}:{advisor:Advisor;onPaper:(id:string)=>void}){
  const [tab,setTab]=useState<'analysis'|'papers'>('analysis');
  const [section,setSection]=useState('当前方向');
  const eligible=advisor.papers.filter(p=>p.eligible);
  const years=unique(eligible.map(p=>p['年份'])).sort();
  const yearOption=useMemo<ChartOption>(()=>({color:palette,tooltip:{trigger:'axis'},grid:{left:38,right:15,top:34,bottom:34},xAxis:{type:'category',name:'年份',nameLocation:'middle',nameGap:25,data:years,axisLine:{lineStyle:{color:'#dce2df'}},axisTick:{show:false},axisLabel:{color:'#748079',fontSize:10,interval:1}},yAxis:{type:'value',name:'论文数（篇）',minInterval:1,nameTextStyle:{color:'#748079',fontSize:11},splitLine:{lineStyle:{color:'#eff2f0'}}},series:[{name:'发表',type:'bar',stack:'count',barMaxWidth:25,data:years.map(y=>eligible.filter(p=>p['年份']===y&&p['文章阶段（发表/预印本）']==='发表').length)},{name:'预印本或发表待核验',type:'bar',stack:'count',barMaxWidth:25,data:years.map(y=>eligible.filter(p=>p['年份']===y&&p['文章阶段（发表/预印本）']!=='发表').length)}]}),[advisor]);
  const themeCounts=useMemo(()=>{const m=new Map<string,number>();for(const p of eligible)m.set(p['统一研究主题'],(m.get(p['统一研究主题'])||0)+1);return [...m].sort((a,b)=>b[1]-a[1]);},[advisor]);
  const themeOption=useMemo<ChartOption>(()=>({tooltip:{trigger:'axis'},grid:{left:153,right:35,top:10,bottom:24},xAxis:{type:'value',name:'篇',minInterval:1,splitLine:{lineStyle:{color:'#eff2f0'}}},yAxis:{type:'category',inverse:true,data:themeCounts.slice(0,6).map(t=>t[0]),axisLine:{show:false},axisTick:{show:false},axisLabel:{color:'#56635c',fontSize:11}},series:[{type:'bar',barWidth:13,itemStyle:{color:'#447eae'},label:{show:true,position:'right',color:'#68756e'},data:themeCounts.slice(0,6).map(t=>t[1])}]}),[themeCounts]);
  const stageCounts=useMemo(()=>{const counts=new Map<string,number>();for(const p of eligible){const key=p['论文对应经历阶段'].includes('待核验')?'阶段待核验':p['论文对应经历阶段'].startsWith('香港大学')?'香港大学任职':p['论文对应经历阶段'].startsWith('Google DeepMind')?'DeepMind任职':p['论文对应经历阶段'];counts.set(key,(counts.get(key)||0)+1);}return [...counts].sort((a,b)=>b[1]-a[1]);},[advisor]);
  const current=advisor.reports.research.find(s=>s.title===section);
  return <div><div className="section-heading"><h2>研究方向</h2><div className="segmented" role="tablist" aria-label="研究视图"><button role="tab" aria-selected={tab==='analysis'} className={tab==='analysis'?'active':''} onClick={()=>setTab('analysis')}>研究轨迹</button><button role="tab" aria-selected={tab==='papers'} className={tab==='papers'?'active':''} onClick={()=>setTab('papers')}>论文目录 <span>{advisor.papers.length}</span></button></div></div>{tab==='papers'?<PaperList advisor={advisor} onPaper={onPaper}/>:<><div className="charts-row"><section><div className="chart-title"><h3>年度论文数量</h3><span className="legend"><i/>发表<i className="blue"/>预印本 / 待核验</span></div><Chart option={yearOption} label="年度已收录论文数，横轴年份，纵轴篇数"/><p className="chart-caption">{years[0]}–{years.at(-1)} · 已收录记录；2026 年尚未结束</p></section><section><div className="chart-title"><h3>主要研究主题分布</h3><span className="muted">按主要主题计数</span></div><Chart option={themeOption} label="主要研究主题论文数量，单位篇"/><p className="chart-caption">前六项主题 · 全部主题见下方主题清单</p></section></div><section className="stage-strip"><h3>经历阶段分布</h3><div className="stage-bars">{stageCounts.map(([name,count],index)=><div key={name}><div><span>{name}</span><strong>{count} 篇</strong></div><div className="stage-track"><span style={{width:`${count/eligible.length*100}%`,background:palette[index%palette.length]}}/></div></div>)}</div><p className="chart-caption">仅按论文署名单位归类；学位与岗位边界不明的单列为待核验。</p></section><div className="report-layout"><nav className="report-nav" aria-label="研究报告章节">{advisor.reports.research.map(s=><button key={s.title} className={section===s.title?'active':''} onClick={()=>setSection(s.title)}>{s.title}<ChevronRight size={14}/></button>)}</nav><article className="report-content"><div className="section-heading"><h3>{current?.title??'尚未整理'}</h3><Badge>证据可追溯</Badge></div>{current&&<Markdown content={current.content} onPaper={onPaper}/>}</article></div></>}</div>;
}

function PaperList({advisor,onPaper,subset}:{advisor:Advisor;onPaper:(id:string)=>void;subset?:string[]}){
  const [search,setSearch]=useState(''),[year,setYear]=useState('全部年份'),[theme,setTheme]=useState('全部主题'),[stage,setStage]=useState('全部阶段'),[page,setPage]=useState(1);
  const papers=advisor.papers.filter(p=>!subset||subset.includes(p['序']));
  const filtered=papers.filter(p=>(p['文章标题']+p['关键词']+p['作者']).toLowerCase().includes(search.toLowerCase())&&(year==='全部年份'||p['年份']===year)&&(theme==='全部主题'||p['统一研究主题']===theme)&&(stage==='全部阶段'||p['文章阶段（发表/预印本）']===stage)).sort((a,b)=>Number(b['年份'])-Number(a['年份'])||Number(a['序'])-Number(b['序']));
  const pages=Math.max(1,Math.ceil(filtered.length/12));const shown=Math.min(page,pages);
  useEffect(()=>setPage(1),[search,year,theme,stage,subset?.join(';')]);
  return <div className="paper-list"><div className="list-controls"><div className="search-input"><Search size={16}/><input placeholder="搜索论文、作者、关键词" aria-label="搜索论文" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="论文年份" value={year} onChange={e=>setYear(e.target.value)}><option>全部年份</option>{unique(papers.map(p=>p['年份'])).reverse().map(y=><option key={y}>{y}</option>)}</select><select aria-label="论文主题" value={theme} onChange={e=>setTheme(e.target.value)}><option>全部主题</option>{unique(papers.map(p=>p['统一研究主题'])).map(t=><option key={t}>{t}</option>)}</select><select aria-label="论文阶段" value={stage} onChange={e=>setStage(e.target.value)}><option>全部阶段</option>{unique(papers.map(p=>p['文章阶段（发表/预印本）'])).map(s=><option key={s}>{s}</option>)}</select></div><div className="list-meta">共 {filtered.length} 篇<span>引用统计：未获取</span></div>{!filtered.length?<Empty text="没有符合条件的论文"/>:<div className="table-scroll"><table className="paper-table"><thead><tr><th>年份</th><th>论文</th><th>主题</th><th>状态</th><th aria-label="打开论文"/></tr></thead><tbody>{filtered.slice((shown-1)*12,shown*12).map(p=><tr key={p['序']} onClick={()=>onPaper(p['序'])}><td className="year-cell">{p['年份']}</td><td><button className="paper-title" onClick={e=>{e.stopPropagation();onPaper(p['序']);}}>{p['文章标题']}</button><div className="paper-subtitle"><span>#{p['序']}</span><span>{p['发表载体']}</span></div></td><td><span className="theme-text">{p['统一研究主题']}</span></td><td><Badge tone={p['文章阶段（发表/预印本）']==='发表'?'green':p['文章阶段（发表/预印本）']==='预印本'?'rose':'amber'}>{p['文章阶段（发表/预印本）']}</Badge><small className="download-status">{p['下载状态']}</small></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div>}<div className="pagination"><span>第 {shown} / {pages} 页</span><button className="icon-btn" title="上一页" aria-label="上一页" disabled={shown===1} onClick={()=>setPage(shown-1)}><ChevronLeft size={18}/></button><button className="icon-btn" title="下一页" aria-label="下一页" disabled={shown===pages} onClick={()=>setPage(shown+1)}><ChevronRight size={18}/></button></div></div>;
}

function PaperDetail({paper:p,advisor,onClose}:{paper:Paper;advisor:Advisor;onClose:()=>void}){
  const [tab,setTab]=useState('研究内容');const issueIds=ids(p['未完成事项序号']);const issues=advisor.issues.filter(i=>issueIds.includes(i['序号']));
  return <Modal title={`论文 #${p['序']}`} onClose={onClose} wide><div className="paper-detail-title"><div className="tags"><Badge>{p['年份']}</Badge><Badge tone="green">{p['统一研究主题']}</Badge><Badge tone={p['文章阶段（发表/预印本）']==='发表'?'green':'rose'}>{p['文章阶段（发表/预印本）']}</Badge></div><h2>{p['文章标题']}</h2><p className="authors">{p['作者']}</p><p className="muted">{p['发表载体']}</p><div className="detail-links">{links(p['论文链接']).slice(0,4).map((url,index)=><External key={url} href={url}>{index===0?'论文原文':`版本 ${index+1}`}</External>)}{p.pdf&&<a className="external" href={p.pdf} target="_blank" rel="noreferrer"><ArrowDownToLine size={15}/>本地 PDF</a>}</div></div><div className="detail-facts"><div><span>被引次数</span><strong>{p['被引次数']}</strong><small>统计日期：{p['引用统计日期']}</small></div><div><span>作者角色</span><strong>{p['是否为一作/通讯']}</strong></div><div><span>全文</span><strong>{p['下载状态']}</strong></div></div><div className="detail-tabs" role="tablist">{['研究内容','作者与单位','证据与核验'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='研究内容'&&<><h3>摘要概述</h3><p className="long-copy">{p['摘要']}</p><h3>研究问题</h3><p>{p['研究问题']}</p><h3>研究内容与方法</h3><p>{p['研究内容']}</p><h3>创新点</h3><p>{p['创新点']}</p><h3>关键词</h3><div className="tags">{p['关键词'].replace('分析提取：','').split('；').map(k=><Badge key={k}>{k}</Badge>)}</div></>}{tab==='作者与单位'&&<><h3>导师论文署名单位</h3><p>{p['导师论文署名单位']}</p><h3>对应经历</h3><p>{p['论文对应经历阶段']}</p><h3>合作者论文署名单位</h3><p className="multiline">{p['合作者姓名及其工作单位']}</p></>}{tab==='证据与核验'&&<><h3>证据位置</h3><p className="multiline evidence">{p['证据位置']}</p><h3>版本与来源说明</h3><p className="multiline evidence">{p['备注']}</p><h3>相关未完成事项</h3>{issues.length?issues.map(i=><div className="issue" key={i['序号']}><Badge tone="amber">事项 {i['序号']}</Badge><p>{i['失败原因']}</p><p className="muted">下一步：{i['下一步建议']}</p></div>):<p>无</p>}</>}</Modal>;
}

function Collaborators({advisor,onPaper,selected,onSelect}:{advisor:Advisor;onPaper:(id:string)=>void;selected:string|null;onSelect:(name:string|null)=>void}){
  const [query,setQuery]=useState(''),[relation,setRelation]=useState('全部关系'),[report,setReport]=useState('学生表现与去向'),[mode,setMode]=useState('名单');
  const people=[...advisor.collaborators].sort((a,b)=>(parseInt(b['共同论文数'])||0)-(parseInt(a['共同论文数'])||0));
  const [includeUnverified,setIncludeUnverified]=useState(false);
  const person=people.find(p=>p['姓名']===selected);
  const filtered=people.filter(p=>(includeUnverified||/^\d+$/.test(p['共同论文数']))&&(p['姓名']+p['当前单位']+p['身份']).toLowerCase().includes(query.toLowerCase())&&(relation==='全部关系'||p['与导师的关系'].includes(relation)));
  const [limit,setLimit]=useState(30);useEffect(()=>setLimit(30),[query,relation]);
  const top=people.filter(p=>/^\d+$/.test(p['共同论文数'])).slice(0,10);
  const graph=useMemo<ChartOption>(()=>({tooltip:{formatter:p=>{const item=p as unknown as {name:string;value?:number};return `${item.name}${item.value?`：${item.value} 篇共同论文`:''}`;}},series:[{type:'graph',layout:'none',left:'18%',right:'18%',top:40,bottom:45,roam:false,emphasis:{focus:'adjacency'},symbolSize:40,label:{show:true,fontSize:11,color:'#37443d'},lineStyle:{color:'#cbd7d1',width:1.5,curveness:0.15},data:[{name:'孔令鹏',x:0,y:0,symbolSize:62,itemStyle:{color:'#167766'},label:{color:'#fff'}},...top.map((p,index)=>({name:p['姓名'],x:160*Math.cos(index*2*Math.PI/top.length-Math.PI/2),y:160*Math.sin(index*2*Math.PI/top.length-Math.PI/2),value:Number(p['共同论文数']),symbolSize:28+Math.min(Number(p['共同论文数']),20),itemStyle:{color:palette[(index%3)+1]},label:{position:'bottom' as const}}))],links:top.map(p=>({source:'孔令鹏',target:p['姓名'],value:Number(p['共同论文数'])}))}]}),[advisor]);
  if(person){const sig=advisor.signatures.filter(s=>s['合作者姓名']===person['姓名']);const first=advisor.collaboratorPapers.filter(p=>p['合作者姓名']===person['姓名']);return <div><button className="back-link" onClick={()=>onSelect(null)}><ArrowLeft size={16}/>返回合作者</button><div className="person-heading"><div><h2>{person['姓名']}</h2><p>{person['当前单位']}</p></div><Badge tone="green">{person['与导师的关系']}</Badge></div><dl className="info-grid person-info"><dt>合作期间身份</dt><dd>{person['身份']}</dd><dt>当前职称</dt><dd>{person['职称']}</dd><dt>可见合作年份</dt><dd>{person['首次合作年份']}–{person['最近合作年份']}</dd><dt>共同研究方向</dt><dd>{person['共同研究方向']}</dd><dt>共同项目</dt><dd>{person['共同项目']}</dd></dl><div className="ratio-row"><SignatureRatio rows={sig} field="导师是否末位" label="导师末位署名比例"/><SignatureRatio rows={sig} field="导师是否通讯" label="导师通讯署名比例"/></div><details className="detail-disclosure"><summary>身份、单位变化与关系证据<ChevronDown size={15}/></summary><h3>历史论文署名单位</h3><p className="multiline">{person['论文署名单位']}</p><h3>关系证据</h3><p className="multiline evidence">{person['关系证据']}</p><h3>待核验问题</h3><p className="multiline">{person['待核验问题']}</p></details><h3 className="subsection-title">共同论文 <span>{person['共同论文数']}</span></h3><PaperList key={person['姓名']} advisor={advisor} onPaper={onPaper} subset={ids(person['共同论文序号'])}/><details className="detail-disclosure"><summary>合作者论文简表（{first.length} 条）<ChevronDown size={15}/></summary>{first.length?first.map((p,index)=><div className="compact-paper" key={index}><strong>{p['论文标题']}</strong><p>{p['年份']} · {p['角色']} · 与孔令鹏合著：{p['是否与目标导师合著']}</p><small>{p['关键词']}</small><details><summary>核验依据</summary><p className="evidence">{p['来源及核验依据']}</p></details></div>):<p>尚未整理</p>}</details></div>;}
  const reportSection=advisor.reports.collaboration.find(s=>s.title===report);
  return <div><div className="section-heading"><h2>合作者</h2><div className="segmented" role="tablist" aria-label="合作者视图">{['名单','合作网络','合作分析'].map(m=><button role="tab" key={m} aria-selected={mode===m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m}</button>)}</div></div>{mode==='合作网络'?<section className="network-section"><h3>已确认重点合作者</h3><Chart option={graph} height={440} label="孔令鹏与共同论文数最多的十位已确认合作者网络" onClick={name=>{if(name!=='孔令鹏')onSelect(name);}}/><p className="chart-caption">边表示已收录论文的共同署名；不等同于指导、项目或人员分工关系。</p></section>:mode==='合作分析'?<div className="report-layout"><nav className="report-nav" aria-label="合作报告章节">{advisor.reports.collaboration.map(s=><button key={s.title} onClick={()=>setReport(s.title)} className={report===s.title?'active':''}>{s.title}<ChevronRight size={14}/></button>)}</nav><article className="report-content"><h3>{report}</h3>{reportSection?<Markdown content={reportSection.content} onPaper={onPaper}/>:<Empty/>}</article></div>:<><div className="list-controls"><div className="search-input"><Search size={16}/><input aria-label="搜索合作者" placeholder="搜索姓名、单位或身份" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="合作关系筛选" value={relation} onChange={e=>setRelation(e.target.value)}><option>全部关系</option><option>导师—学生</option><option>共同指导</option><option>博士后</option><option>论文合作者</option><option>同门</option></select></div><div className="collaborator-scope"><label><input type="checkbox" checked={includeUnverified} onChange={e=>setIncludeUnverified(e.target.checked)}/>显示身份待核验的原始署名</label><p>已确认身份的合作者按人合并；其他记录按单篇保留，不作为人数统计。</p></div><div className="list-meta">{filtered.length} {includeUnverified?'条合作者记录':'位已核验合作者'}<span>按共同论文数排序</span></div>{filtered.length?<div className="table-scroll"><table className="collab-table"><thead><tr><th>合作者</th><th>当前单位 / 身份</th><th>关系</th><th>共同论文</th><th>可见年份</th><th/></tr></thead><tbody>{filtered.slice(0,limit).map(p=><tr key={p['姓名']} onClick={()=>onSelect(p['姓名'])}><td><button className="person-name" onClick={e=>{e.stopPropagation();onSelect(p['姓名']);}}>{p['姓名']}</button></td><td><span>{p['当前单位']}</span><small>{p['身份']}</small></td><td><Badge tone={p['与导师的关系'].includes('待核验')?'amber':p['与导师的关系']==='论文合作者'?'neutral':'green'}>{p['与导师的关系']}</Badge></td><td><strong>{p['共同论文数']}</strong></td><td className="muted">{p['首次合作年份']}–{p['最近合作年份']}</td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div>:<Empty text="没有符合条件的合作者"/>}{filtered.length>limit&&<div className="load-more"><button className="text-button" onClick={()=>setLimit(limit+30)}>显示更多<ChevronDown size={16}/></button><span>{limit} / {filtered.length}</span></div>}</>}</div>;
}
function Issues({advisor,onClose,onPaper}:{advisor:Advisor;onClose:()=>void;onPaper:(id:string)=>void}){const [search,setSearch]=useState('');const filtered=advisor.issues.filter(i=>(i['论文标题']+i['失败原因']+i['序号']).toLowerCase().includes(search.toLowerCase()));return <Modal title="未完成事项" onClose={onClose} wide><div className="search-input"><Search size={16}/><input placeholder="搜索论文或问题" aria-label="搜索未完成事项" value={search} onChange={e=>setSearch(e.target.value)}/></div><p className="muted">共 {filtered.length} 条 · 采集日期 {advisor.info['抓取日期']}</p>{filtered.map(i=>{const p=advisor.papers.find(p=>p['文章标题']===i['论文标题']);return <div className="issue" key={i['序号']}><div className="tags"><Badge tone="amber">事项 {i['序号']}</Badge><span>{i['年份']}</span></div><h3>{p?<button className="inline-link" onClick={()=>onPaper(p['序'])}>{i['论文标题']}</button>:i['论文标题']}</h3><p>{i['失败原因']}</p><p className="muted">下一步：{i['下一步建议']}</p><details><summary>已查来源</summary><div className="source-list">{links(i['尝试过的链接']).map((url,n)=><External key={n} href={url}>{url}</External>)}</div></details></div>;})}</Modal>;}
